# build a docker image with android build tooling
on:
  workflow_dispatch:
    inputs:
      image:
        default: ghcr.io/viam-labs/rdk-apk
      tag:
        default: latest

jobs:
  base-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v4
    - name: build
      run: docker build -t ${{ inputs.image }}:${{ inputs.tag }} --label org.label-schema.vcs-ref=$(git rev-parse HEAD) .
    - name: push
      run: docker push ${{ inputs.image }}:${{ inputs.tag }}
