# build a docker image with android build tooling
on:
  workflow_dispatch:
    inputs:
      image:
        default: ghcr.io/viam-labs/rdk-apk
      tag:
        default: latest

jobs:
  base-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v4
    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ inputs.image }}
    - uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ inputs.image }}:${{ inputs.tag }}
        labels: ${{ steps.meta.outputs.labels }}
