# build 
on:
  workflow_dispatch:
    inputs:
      repository:
        default: viamrobotics/rdk
      ref:
        default: main

jobs:
  daily:
    runs-on: ubuntu-latest
    container: ghcr.io/viam-labs/rdk-apk
    steps:
    - uses: actions/checkout@v4
      with:
        path: rdk-apk
    - uses: actions/checkout@v4
      with:
        repository: ${{ inputs.repository }}
        ref: ${{ inputs.ref }}
        path: rdk
    # todo: put tflite and x264 in same etc/android/prefix, then try pkgconfig
    # todo: look at short-lived cache of etc/android/prefix
    - name: build tflite
      working-directory: rdk
      run: ANDROID_NDK=$NDK_ROOT KEEP_TFLITE_SRC=1 etc/android/build-tflite.sh
    - name: build x264
      working-directory: rdk
      run: make etc/android/prefix/{aarch64,x86_64}
    - name: build AAR
      working-directory: rdk
      run: CGO_CFLAGS="-I $HOME/tensorflow/tensorflow-2.12.0" PLATFORM_NDK_ROOT=$NDK_ROOT NDK_ROOT=$NDK_ROOT make droid-rdk.aar
    # todo: pass down APK version information
    - name: build APK
      working-directory: rdk-apk
      run: |
        export RDK_PATH=$(realpath ../rdk)
        ./gradlew assembleDebug
        find | grep apk
